/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class danxx_ndk_JniH */

#ifndef _Included_danxx_ndk_JniH
#define _Included_danxx_ndk_JniH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     danxx_ndk_JniH
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_danxx_ndk_JniH_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
